export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_QUANTITY_PRODUCT = 'SET_QUANTITY_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
